apiVersion: v1
kind: Service
metadata:
  name: knote-service
  namespace: knote-app
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer # Change to NodePort if LoadBalancer is not needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-deployment
  namespace: knote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: heder24/my-app:knote
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ROOT_USER
              value: mykey
            - name: MINIO_ROOT_PASSWORD
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
