apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: knote-app
spec:
  encryptedData:
    .dockerconfigjson: AgARNLbd0z9Sh2SvQyAm84Ua0k/TUdxX60d+iLdIZQ1YCBrN5yN4zYfB9r3OTA4qDpLmCwg1Tt+sn1Qoqzv6/Ia2t/PCJwc+lplhB8WpT7EKyaI83+HIkQ8KsA7Meiv+MncBiOIls/ZmCaDnpKD7m3BOVbTsqNX3Y8IwLM6UJ2fPSbsC0bHSyheUxmPzbfoGnoFqiw8UgmcCsp1F0uAsf3ElvlXP8+2YiVgujVDuazVv5FNK9QHFhrY6JBQlEb4kQk+1CvO2KjcCqBNsLL6rrfM07+kIIoH99c8ImCAnVZyk3dlIWnCebLc1Ctwu9GxFJdmSpG2Arb0/O/B4/pDAZIKjwqGwls16DQZzSbBJpEDZ+Ek0MSEfuKBZz1g/z5wdng8h8kemZ8lHdt4RvapYCQGlWeIzQeEbM4q4FizLElrPJscMyyVOEeGoVp/hdEEGxKMckXXjLqMEOM+nwI+J851L91vpG+NeaJ1SjWLuvvAMYYHj2WKCZrwQMyMcG9RwjcZ8mF7TtAcvjpGmCDjTDw8aJs/9Dj/O1nN6nkRcSu+7WkdK1TzAfDUEFr4rP7/2MgatKadK3Z21FeqnlY96UMsAkNkwz3zsOCyx18WVuCp4UERupVMsR+xcHpiiFrL5DcjUaWPky8fFl0NSe7+mqnFjuUFEq3On4j68I8mxUCTZQiBzJiEx5AErKimx5nLEizkn3NcIqwjgt2/RMxcw8wJJI/If4hWkn5I3EXA0ifM4JWGGfRFuX2heLWRNdL/8CySo9eCL8FzKK4PjlIgGt1MoWMhNzs38oG/FsZPHtNg0ydvYZMFZqWWjjmdsg5XF8M19O3A=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: knote-app
    type: kubernetes.io/dockerconfigjson
status: {}

